config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  root to:'toppages#index'
  devise_for :users
  resources :users, only:[:show, :edit, :update]
  resources :items, only: [:new, :show]
  resources :favorites, only: [:create, :destroy]
  resources :details, only: [:index, :new, :create, :edit, :update, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :favorite
  
  validates :name, length: { maximum: 100 }
  validates :purchase_date, length: { maximum: 100 }
  validates :place, length: { maximum: 100 }
  validates :person, length: { maximum: 100 }
  validates :reason, length: { maximum: 300 }
  validates :way, length: { maximum: 100 }
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
  
  has_one :detail, dependent: :destroy
  validates :user_id, presence: true,  uniqueness: { scope: :item_id } 
 
end

app/models/item.rb
class Item < ApplicationRecord
  validates :code, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :url, presence: true
  validates :image_url, presence: true
  
  has_many :favorites, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  mount_uploader :image, ImageUploader
  
  has_many :items, dependent: :destroy, through: :favorites
  has_many :favorites, dependent: :destroy
  has_many :fav_items, through: :favorites, source: :item
  
  def fav(item)
    favorites.find_or_create_by(item_id: item.id)
  end
  
  def unfav(item)
    favorites.find_by(item_id: item.id).destroy
  end
  
  def fav?(item)
    self.fav_items.include?(item)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
  def read(result)
    code = result['itemCode']
    name = result['itemName']
    price = result['itemPrice']
    url = result['itemUrl']
    image_url = result['mediumImageUrls'].first.gsub('?_ex=128x128', '')
    {code: code, name: name, price: price, url: url, image_url: image_url}
  end
  
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_detail, only: [:edit, :update, :destroy]
  
  def index
    @details = []
    @favorites = Favorite.where(user_id: current_user.id)
    
    if @favorites 
      @favorites.each do |favorite|
        @detail = Detail.find_by(favorite_id: favorite.id) 
        @details << @detail
      end
    end
    
    @exist_details = @details.compact
  end
  
  def new
    @favorite = Favorite.find_by(id: params[:format])
    @item = Item.find_by(id: @favorite.item_id)
    @detail = Detail.new
  end  
  
  def create
    @favorite = Favorite.find_by(id: params[:favorite_id])
    @item = Item.find_by(id: @favorite.item_id)
    @detail = @favorite.build_detail(detail_params)
  
    if @favorite.user_id == current_user.id
      @detail.save
    end
    
    if @detail.save 
      flash[:success] = "4wを登録しました。"
      redirect_to item_path(@item)
    else
      flash.now[:danger] = "4wの登録に失敗しました。"
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    @favorite = Favorite.find_by(id: @detail.favorite_id)
    @item = Item.find_by(id: @favorite.item_id)
    
    if @detail.update(detail_params)
      flash[:success] = "5w1hの編集が完了しました。"
      redirect_to item_path(@item)
    else
      flash.now[:danger] = "5w1hの編集に失敗しました。"
      render 'edit'
    end
    
  end
  
  def destroy
    @detail.destroy
    flash[:success] =  '5w1hを削除しました。'
    redirect_back(fallback_location: item_path(@detail))
  end
  
  private
  
  def set_detail
    @detail = Detail.find(params[:id])
  end
  
  def detail_params
    params.require(:detail).permit(:favorite_id, :name, :purchase_date, :place, :person, :reason,  :way)
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @item = Item.find_or_initialize_by(code: params[:item_code])
    
    unless @item.persisted?
      results = RakutenWebService::Ichiba::Item.search(itemCode: @item.code)
      @item = Item.new(read(results.first))
      @item.save
    end
    
    current_user.fav(@item)
    flash[:success] = "お気に入り登録しました。"
    
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @item = Item.find(params[:item_id])
    
    current_user.unfav(@item)
    
    flash[:success] = "お気に入り登録を解除しました。"
    
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @items = []
    @keyword = params[:keyword]
    
    if @keyword
      results = RakutenWebService::Ichiba::Item.search({keyword: @keyword, imageFlag: 1, hits: 20})
     
      results.each do |result|
        @item = Item.find_or_initialize_by(read(result))
        @items << @item
      end
      
    end
    
  end
  
  def show
    @item = Item.find(params[:id])
    @favorite = Favorite.find_by(user_id: current_user.id, item_id: @item.id)
    @detail = Detail.find_by(favorite_id: @favorite.id)
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  def index
    @items = Item.page(params[:page]).per(9).order('updated_at DESC')
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]
  
  def show
    @items = @user.items.page(params[:page]).per(9)
  end
  
  def edit
  end
  
  def update

    if current_user == @user
      
      if @user.update(user_params)
        flash[:success] = "ユーザー情報を編集しました。"
        redirect_to @user
      else
        flash[:danger] = "ユーザー情報の編集に失敗しました。"
        render :edit
      end
      
    else
      redirect_to root_url
    end
    
  end
  
  private
  
  def set_user
   @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/details/_detail.html.erb
<div class="detail">
  <div class="inner">
    <% unless detail.name.empty? %>
    <div class="detail-item">
      <p class="detail-item-tag">What</p>
      <div class="detail-item-contents txtm">
        <%= detail.name %>
      </div>
    </div>
    <% end %>
    <% unless detail.purchase_date.empty? %>
    <div class="detail-item">
      <p class="detail-item-tag">When</p>
      <div class="detail-item-contents txtm">
        <%= detail.purchase_date %>
      </div>
    </div>
    <% end %>
    <% unless detail.place.empty? %>
    <div class="detail-item">
      <p class="detail-item-tag">Where</p>
      <div class="detail-item-contents txtm">
        <%= detail.place %>
      </div>
    </div>
    <% end %>
    <% unless detail.person.empty? %>
    <div class="detail-item">
      <p class="detail-item-tag">Who</p>
      <div class="detail-item-contents txtm">
        <%= detail.person %>
      </div>
    </div>
    <% end %>
    <% unless detail.reason.empty? %>
    <div class="detail-item">
      <p class="detail-item-tag">Why</p>
      <div class="detail-item-contents txtm">
        <%= detail.reason %>
      </div>
    </div>
    <% end %>
    <% unless detail.way.empty? %>
    <div class="detail-item">
      <p class="detail-item-tag">How</p>
      <div class="detail-item-contents txtm">
        <%= detail.way %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/details/edit.html.erb
<div class="detail-edit cmn-form">
  <div class="inner">
    <h1 class="ttl">5w1hの編集</h1>
    <%= form_for(@detail) do |f| %>
    <div class="form-item">
      <%= f.label :name, 'What', class: "txtm" %>
      <%= f.text_field :name,  :placeholder => "何を買いたいですか？" %>
    </div>
    <div class="form-item input-group" data-target-input="nearest">
      <%= f.label :purchase_date, 'When', class: "txtm" %>
      <%= f.text_field :purchase_date, id: "purchase_date", class: "form-control datepicker", data: { target: '#purchase_date'} ,:placeholder => "いつ買いたいですか？" %>
      <div class="input-group-append" data-target="#purchase_date" data-toggle="datetimepicker">
        <div class="input-group-text">
          <i class="fa fa-calendar">カレンダー</i>
        </div>
      </div>
    </div>
    <div class="form-item">
      <%= f.label :place, 'Where', class: "txtm" %>
      <%= f.text_field :place, :placeholder => "どこで買いたいですか？" %>
    </div>
    <div class="form-item">
      <%= f.label :person, 'Who', class: "txtm" %>
      <%= f.text_field :person, :placeholder => "誰に買いますか？" %>
    </div>
    <div class="form-item">
      <%= f.label :reason, 'Why', class: "txtm" %>
      <%= f.text_area :reason, :placeholder => "なぜ買いたいですか？" %>
    </div>
    <div class="form-item">
      <%= f.label :way, 'How', class: "txtm" %>
      <%= f.text_field :way, :placeholder => "どのようにして買いたいですか？" %>
    </div>
    <%= f.submit '完了', class: "btnl" %>
    <% end %>
  </div>
</div>

app/views/details/index.html.erb
<% if @details %>
<div class="details">
  <div class="inner">
    <h1 class="ttl">item5w1h一覧</h1>
    <% @exist_details.each do |detail| %>
    <%= render 'detail', detail: detail %>
    <div class="btns">
      <%= link_to "5w1h編集", edit_detail_path(detail), class: "btn" %>
      <%= link_to "5w1h削除", detail_path(detail), method: :delete, class: "btn" %>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/details/new.html.erb
<div class="detail-new cmn-form">
  <div class="inner">
    <h1 class="ttl">5w1h新規作成</h1>
    <%= form_for(@detail) do |f| %>
    <%= hidden_field_tag :favorite_id, @favorite.id  %>
    <div class="form-item">
      <%= f.label :name, 'What', class: "txtm" %>
      <%= f.text_field :name, value: @item.name,  :placeholder => "何を買いたいですか？" %>
    </div>
    <div class="form-item input-group" data-target-input="nearest">
      <%= f.label :purchase_date, 'When', class: "txtm" %>
      <%= f.text_field :purchase_date, id: "purchase_date", class: "form-control datepicker", data: { target: '#purchase_date'} ,:placeholder => "いつ買いたいですか？" %>
      <div class="input-group-append" data-target="#purchase_date" data-toggle="datetimepicker">
        <div class="input-group-text">
          <i class="fa fa-calendar">カレンダー</i>
        </div>
      </div>
    </div>
    <div class="form-item">
      <%= f.label :place, 'Where', class: "txtm" %>
      <%= f.text_field :place, :placeholder => "どこで買いたいですか？" %>
    </div>
    <div class="form-item">
      <%= f.label :person, 'Who', class: "txtm" %>
      <%= f.text_field :person, :placeholder => "誰に買いますか？" %>
    </div>
    <div class="form-item">
      <%= f.label :reason, 'Why', class: "txtm" %>
      <%= f.text_area :reason, :placeholder => "なぜ買いたいですか？" %>
    </div>
    <div class="form-item">
      <%= f.label :way, 'How', class: "txtm" %>
      <%= f.text_area :way, :placeholder => "どのようにして買いたいですか？" %>
    </div>
    <%= f.submit '完了',class: "btnl" %>
    <% end %>
  </div>
</div>

app/views/favorites/_fav_button.html.erb
<% if current_user.fav?(item) %>
<%= form_tag(favorite_path(item.id), method: :delete) do %>
<%= hidden_field_tag :item_id, item.id %>
<%= submit_tag '登録解除', class: 'btn' %>
<% end %>
<% else %>
<%= form_tag(favorites_path) do %>
<%= hidden_field_tag :item_code, item.code %>
<%= submit_tag '登録', class: 'btn' %>
<% end %>
<% end %>

app/views/items/_items.html.erb
<% if items %>
<div class="items">
  <% items.each do |item| %>
  <div class="item">
    <div class="item-top">
      <div class="item-img">
        <img src=<%= item.image_url %>>
      </div>
    </div>
    <div class="item-btm">
      <% if item %>
      <p class="item-name">
        <%= item.name %>
      </p>
      <p class="item-price">
        <%= item.price %>円
      </p>
      <div class="btns">
        <% if user_signed_in? %>
        <%= render 'favorites/fav_button', item: item %>
        <% if current_user.fav?(item) %>
        <%= link_to "商品詳細", item_path(item), class: "btn" %>
        <% end %>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/items/new.html.erb
<div class='item-search'>
  <div class="inner">
    <h1 class="ttl">アイテムを探す</h1>
    <div class="form-item">
      <%= form_tag(new_item_path, method: :get) do %>
      <%= text_field_tag :keyword, @keyword, placeholder: "キーワードを打ち込んでください" %>
    </div>
    <%= submit_tag '商品を検索', class: "btnl" %>
    <% end %>
    <%= render 'items', items: @items %>
  </div>
</div>

app/views/items/show.html.erb
<div class="fav">
  <div class="inner">
    <h1 class="ttl">お気に入りアイテム</h1>
    <div class="fav-item">
      <p class="fav-item-name">
        <%= link_to @item.name, @item.url %>
      </p>
      <div class="fav-item-img">
        <img src="<%= @item.image_url %>">
      </div>
      <% unless @detail %>
      <%= link_to "5w1h新規作成", new_detail_path(@favorite), class: "btn"  %>
      <% else %>
      <%= render 'details/detail', detail: @detail %>
      <div class="btns">
        <%= link_to "5w1h編集", edit_detail_path(@detail),  class: "btn" %>
        <%= link_to "5w1h削除", detail_path(@detail),  method: :delete,  class: "btn" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="inner">
    <div class="copy txtxs">
      <small>© 2020 ITEM5W1H.</small> 
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="header-logo">
    <%= link_to "5w1h", root_url ,class: "txtl" %>
    <p class="header-sub-txt txts">あなたに合った商品を</p>
  </div>
  <div class="drawer">
    <div class="drawer-icon">
      <span class="drawer-open">
        <span class="drawer-icon-parts"></span>
      </span>
      <span class="drawer-close">
        <span class="drawer-icon-parts"></span>
      </span>
    </div>
    <nav class="drawer-nav">
      <ul class="drawer-list">
        <% if user_signed_in? %>
        <li class="menu-item txts">
          <%= link_to "アイテムを探す", new_item_path %>
        </li>
        <li class="menu-item txts">
          <%= link_to 'マイページ/お気に入り商品一覧', user_path(current_user) %>
        </li>
        <li class="menu-item txts">
          <%= link_to "5w1hを見る", details_path %>
        </li>
        <li class="menu-item txts">
          <%= link_to 'パスワード変更', edit_user_registration_path(current_user) %>
        </li>
        <li class="menu-item txts">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
        <li class="menu-item txtm">
          <%= link_to "ログイン",new_user_session_path %>
        </li>
        <li class="menu-item txtm">
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
  <nav class="global-nav">
    <ul class="global-list">
      <% if user_signed_in? %>
      <li class="menu-item txts">
        <%= link_to "アイテムを探す", new_item_path %>
      </li>
      <li class="menu-item txts">
        <%= link_to "5w1hを見る", details_path %>
      </li>
      <li class="menu-item txts">
        <%= link_to 'パスワード変更', edit_user_registration_path(current_user) %>
      </li>
      <li class="menu-item txts">
        <%= link_to 'マイページ/お気に入り商品一覧' , user_path(current_user) %>
      </li>
      <li class="menu-item txts">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
      <% else %>
      <li class="menu-item txtm">
        <%= link_to "ログイン",new_user_session_path %>
      </li>
      <li class="menu-item txtm">
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Item5w1h</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="main">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/toppages/index.html.erb
<div class="top">
  <div class="inner">
    <% if user_signed_in? %>
    <h1 class="ttl">トップページ</h1>
    <p class="login-name">現在
      <%= current_user.name %>さんがログインしています
    </p>
    <p class="email-address">メールアドレス:
      <%= current_user.email %>
    </p>
    <%= render 'items/items', items: @items %>
    <%= paginate @items %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btnl" %>
    <% else %>
    <h1 class="ttll">Item5w1hへ
      <br>ようこそ
    </h1>
    <p class="desc-5w1h txtm">Itme5w1hとは?
      <br>あなたはつい衝動買いしてしまうことはありませんか？
      <br>Item5wではお気に入りの商品に詳細をつけることができます。
      <br>What(何を)、When(いつ)、Where(どこで)、Who（誰が）、Why（なぜ）、How（どのように）
      <br>の5つのWと1つのHの詳細をつけて、本当に欲しい商品を見つけよう！ 
    </p>
    <%= link_to "ログイン",new_user_session_path, class: "btnl" %>
    <%= link_to "新規登録", new_user_registration_path, class: "btnl" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit cmn-form">
  <div class="inner">
    <h1 class="ttl">ユーザー編集</h1>
    <%= form_for(@user) do |f| %>
    <div class="user-edit-img">
      <% if @user.image? %>
      <%= image_tag @user.image.url(:thumb) %>
      <% else %>
      <%= image_tag "no_image", :size => '100x100' %>
      <% end %>
    </div>
    <button type="button" class="btn">
      <%= f.file_field :image %>
    </button>
    <div class="form-item">
      <%= f.text_field :name, :placeholder => "name" %>
    </div>
    <%= f.submit '変更', class: "btnl" %>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="user">
  <div class="inner">
    <h1 class="ttl">マイページ/お気に入り商品一覧</h1>
    <p class="user-name txtl">
      <%= @user.name %>
    </p>
    <div class="user-img">
      <% if @user.image? %>
      <%= image_tag @user.image.url(:thumb) %>
      <% else %>
      <%= image_tag "no_image", :size => '200x200' %>
      <% end %>
    </div>
    <%= link_to "ユーザー編集", edit_user_path(current_user), class: "btn" %>
    <%= render 'items/items', items: @items %>
    <%= paginate @items %>
  </div>
</div>